<?php

/**
 * @file
 * Install, update and uninstall functions for the Slick Development module.
 */

/**
 * Implements hook_uninstall().
 */
function slick_devel_uninstall() {
  variable_del('slick_devel');
  variable_del('slick_devel_debug');
  variable_del('slick_devel_disable');
  variable_del('slick_devel_replace');
  if (variable_get('slick_devel_load', FALSE)) {
    variable_del('slick_devel_load', TRUE);
  }
}
